apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devops-ecommerce
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/vasigaran-P/devops-ecommerce
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: devops-ecommerce
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
