sonar.projectKey=node-microservices
sonar.projectName=Node Microservices
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/test/**,**/coverage/**,**/*.yml,**/Dockerfile
sonar.sourceEncoding=UTF-8
sonar.qualitygate.wait=true
sonar.coverage.exclusions=**/*
