apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
  namespace: devops-ecommerce
type: Opaque
stringData:
  MONGO_URI: mongodb://admin:admin1234@mongo-service:27017
  JWT_SECRET: your-jwt-secret-key-here
  PORT: "3001"
