apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: devops-ecommerce
type: Opaque
stringData:
  MONGO_ROOT_USERNAME: admin
  MONGO_ROOT_PASSWORD: admin1234
  MONGO_URI: mongodb://admin:admin1234@mongo-service:27017
