apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: devops-ecommerce
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: 474418737424.dkr.ecr.ap-south-1.amazonaws.com/product-service:c038777
          ports:
            - containerPort: 3002
          envFrom:
            - secretRef:
                name: product-secret
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
